    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    zn "USER"
    do EnableDeepSee^%SYS.cspServer("/csp/user/")

    ; install samples-bi for cubes to test with
    zpm "install samples-bi"
    
    ; load classes
    zpm "load /opt/irisapp"
    Do ##class(PivotToJupyter.CustomKPIAction).UpdateActionClass()

    set ^PivotToJupyter("jupyter-hostname") = "localhost"
    set ^PivotToJupyter("jupyter-port") = 61888
